### ISSUE TITLE
Prepare kinematic data and time to last merger as tf dataset

### ISSUE THREAD

**Issue by EiffL** [EiffL/sfh-inference-hackathon#5]

**Comment by ppfn** [comment]
commit 122bab3d35264ae9d346d26e97af3fd00632a81a add a package for galaxy mergers.

**Comment by ppfn** [comment]
Merge pull request #11 add the kinetic module into the sfh.datasets.mergers package.

**Comment by ppfn** [comment]
@Siouar, can you work on generating the full dataset on Jean-Zay ?
If I remember well, last time we tried we had connection issues and the process was interrupted.

To do so I think a simple python script containing:
```python
import tensorflow as tf
import tensorflow_datasets as tfds
from sfh.datasets.mergers import kinetic

ds = tfds.load('MergersKinetic', split='train')
```

should be launched from a screen session on one of the login node of Jean-Zay.

**Comment by EiffL** [comment]
I'm running this dataset in full at the moment, and will place it in a common directory for all of us to easily use.

**Comment by ppfn** [comment]
Commit a9f30bddac1b8fc89f877902b24ed151df3bb3e6 add different BUILDER_CONFIGS to the dataset.
That way, one can call the `tfds.load()` function with different sizes for the dataset:
```python
ds = tfds.load('MergersKinetic/tiny') # max 250 examples in the dataset
ds = tfds.load('MergersKinetic/small') # max 2,500 examples in the dataset
ds = tfds.load('MergersKinetic/medium') # max 5,000 examples in the dataset
ds = tfds.load('MergersKinetic/full') # max 1,000,000 examples in the dataset (arbitrary large value)
```

**Comment by ppfn** [comment]
Created a new branch `variant_kinetic_dataset` where kinetic.py includes BUILDER_CONFIGS for the MergersKinetic dataset are present

**Comment by EiffL** [comment]
I thinink this is all done! Thanks guys!
