### ISSUE TITLE
Prepare dataset for SFH and mass history as tf dataset

### ISSUE THREAD

**Issue by EiffL** [EiffL/sfh-inference-hackathon#7]

**Comment by yannick1974** [comment]
There is still some problem of some CSV SFH missing some SnapNUm, e.g. TNG100_mainprojenitors_102694.csv is missing SnapNUm 13.

**Comment by 16Aghnar** [comment]
Ok, so I see 2 options :

1. We write 0 anywhere a SnapNum is missing, and make a boolean feature for to tell wether the timestep has been inserted or not. So imagine `t = [1, 3], d=[2.5, 1.5]`, then the dataset sequence will be : `t = [0, 1, 2, 3], d=[0, 2.5, 0, 1.5], b=[0., 1., 0., 1.]` 
2. We write as many 0 we need to get N=100 before the oldest SnapNum. In this case we can still use N_age and don't need a boolean sequence. `t = [1, 3], d=[2.5, 1.5]` => `t = [0, 0, 1, 3], d=[0, 0, 2.5, 1.5], N_age=2`
