### ISSUE TITLE
Implement a generative model for time series to model SFH

### ISSUE THREAD

**Issue by EiffL** [EiffL/sfh-inference-hackathon#9]
This task is to try to implement a generative model for 1D data

Here are a few pointers:

- [notebook](https://colab.research.google.com/drive/1wPNS0gBetVUk2EAK8_5HJmrAT_o476L0?usp=sharingv) with a 1d temporal network.

**Comment by EiffL** [comment]
I have implemented a Keras shift layer to break the connection between present and 
https://colab.research.google.com/drive/1JoYHMHWvO151AW2E833uffPl7h7tz7SY?usp=sharing

**Comment by 16Aghnar** [comment]
Work in progress on pixelcnn/tfds branch. Currently the training crashes because of incompatible shape.

**Comment by 16Aghnar** [comment]
Bug fixed, we have a training now !

**Comment by EiffL** [comment]
Allllez!!!!

**Comment by EiffL** [comment]
Hereer is my notebook https://github.com/EiffL/sfh-inference-hackathon/blob/u/EiffL/pixelcnn/notebooks/PixelCNN_experiments_EiffL.ipynb

**Comment by EiffL** [comment]
@mhuertascompany how cool is this :-D ?
![image](https://user-images.githubusercontent.com/861591/145494494-1eea8e9b-4839-4529-9deb-b0908ca6cbb8.png)
SFH drawn from a pixelcnn conditioned only on SED

**Comment by EiffL** [comment]
![image](https://user-images.githubusercontent.com/861591/145494721-509a71ff-55ee-4148-ab7b-c10d76d92dcd.png)
![image](https://user-images.githubusercontent.com/861591/145494946-d4218cf0-0176-4a6e-b4c6-ac0a2bc5577c.png)
![image](https://user-images.githubusercontent.com/861591/145495115-22e4d6f2-5f0a-4cf5-8189-2f86136d6c52.png)

**Comment by mhuertascompany** [comment]
yeahhh!!!!
so cool.
let's write a paper :))

**Comment by EiffL** [comment]
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/861591/145554716-89709352-23e1-47cf-a7bc-36addad0cbc0.gif)
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/861591/145554721-6d3b22e3-fd90-49ea-b5c9-a6513cce086c.gif)

**Comment by laurilaatu** [comment]
VAE predictions don't have the fine detail of the input sample. What could be some ways to fix this issue?

![sfr_vae1](https://user-images.githubusercontent.com/19837180/159227937-f1158493-966c-4d4d-9419-02db749a2963.png)

**Comment by EiffL** [comment]
I'm going to close this issue for now so that we can start fresh
